baseurl = "https://trails-we-hike.appspot.com/"
languageCode = "en-us"
title = "Trails We Hike"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Trails We Hike"
	description = "We capture hiking, backpacking, and camping experiences in the form of video/film, still photography, and acoustic music."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Hugo Creative Theme"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Your awesome slogan"
		subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We're Trails We Hike"
		description = "We're **Trails We Hike**, folks dedicated to capturing camping, backpacking, and hiking experiences and publishing them in as many forms as possible"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Sturdy Templates"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@trailswehike.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
